# @format
name: cinezza
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  get_storage: ^2.1.1
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.2
  share_plus: ^12.0.1
  shimmer: ^3.0.0
  video_player: ^2.10.1
  screen_brightness: ^2.1.7
  wakelock_plus: ^1.4.0
  flutter_volume_controller: ^1.3.4
  just_audio: ^0.10.5
  connectivity_plus: ^7.0.0
  shared_preferences: ^2.5.3
  device_info_plus: ^12.3.0
  uuid: ^4.5.2
  confetti: ^0.8.0
  razorpay_flutter: ^1.4.0
  google_fonts: ^6.3.3
  webview_flutter: ^4.13.0
  ota_update: ^7.0.2
  permission_handler: ^12.0.1
  google_mobile_ads: ^6.0.0
  flutter_native_splash: ^2.4.7
  intl: ^0.20.2
  lottie: ^3.3.2
  carousel_slider: ^5.1.1
  internet_connection_checker: ^1.0.0+1
  firebase_core: ^4.3.0
  onesignal_flutter: ^5.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/jsons/

# --------------------------------------------------
# ðŸš€ Flutter Splash Screen Configuration (Correct place)
# --------------------------------------------------

flutter_native_splash:
  color: "#000000" # Background color
  image: assets/images/splash.png # Transparent 512x512 or 1024x1024 image

  android: true
  ios: true

  android_12:
    color: "#000000"
    image: assets/images/splash.png
    icon_background_color: "#000000"
    android_gravity: center
